### ISSUE TITLE
Error abrir jupyter

### ISSUE THREAD

**Issue by jcechavarri** [IIC2233/syllabus-2018-2#200]
Hola!
Al intentar abrir jupyter notebook me tira error.

Intenté desinstalar jupyter vía pip y luego volver a instalarlo y sigo obteniendo el mismo error. También intente por Anaconda sin resultados. Agradecería ayuda

![image](https://user-images.githubusercontent.com/42159312/45047873-bb3cdb00-b050-11e8-9851-eef1117a556a.png)

**Comment by naquiroz** [comment]
Hola! Pudiste resolver tu problema?

**Comment by jcechavarri** [comment]
@naquiroz Hola! No, no lo he podido resolver. Volví a desinstalar anaconda y volver a instalarlo marcando la opción que **no** es por defecto y tampoco. Intente reinstalando con pip sin guardar cache y tampoco.

**Comment by naquiroz** [comment]
@jcechavarri :thinking:  Te recomiendo probar con lo siguiente.

1. **Borrar completamente anaconda**. Anaconda hace cosas feas en tu computador por detrás, que se supone que te hacen la vída mas facil, pero es mentira, lo hace todo más dificil (en mi humilde opinión). Buscando en internet, encontré [este link](https://stackoverflow.com/questions/29337928/how-to-remove-anaconda-from-windows-completely) que dice que debes ir a `C:\Users\tu_nombre_usuario\Anaconda3` (Si tu versión no es 3, pon la versión o versiones que tengas), y debes correr `Uninstall-Anaconda.exe`
2. Dirígete [python.org](https://python.org) e instala la versión de python para este curso. **Nota**: En el instalador recuerda activar la opción que dice algo del `PATH`.
3. Instala lo necesario para este curso, (y jupyter). Puedes encontrar lo necesario [aquí](https://github.com/IIC2233/syllabus/wiki/Software-Obligatorio).
4. Prueba si te funciona!

Me comentas como te resulta

Saludos :v:

**Comment by jcechavarri** [comment]
@naquiroz Tampoco funcionó. :(

**Comment by naquiroz** [comment]
Te sigue tirando el mismo error?

**Comment by jcechavarri** [comment]
@naquiroz Logre solucionarlo! Tuve que restaurar desde powershell, ahora me tira el siguiente error (en jupyter)

```
Traceback (most recent call last):
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\jcech\appdata\local\programs\python\python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado```

**Comment by naquiroz** [comment]
@jcechavarri Intenta correr el siguiente comando en powershell con **permisos de administrador**

`python -m ipykernel install --user`

**Comment by jcechavarri** [comment]
@naquiroz Gracias! Solucionado

**Comment by naquiroz** [comment]
@jcechavarri  Denada!

:v:
